name: tests

on:
  - push
  - pull_request

jobs:
  test:
    timeout-minutes: 3

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4']
        laravel: [9, 10, 11, 12]
        exclude:
          - php: '8.0'
            laravel: 10
          - php: '8.0'
            laravel: 11
          - php: 8.1
            laravel: 11
          - php: 8.3
            laravel: 9
          - laravel: 12
            php: '8.0'
          - laravel: 12
            php: 8.1
          # Исключаем запуск Laravel 9 на PHP 8.4 (несовместимы)
          - php: '8.4'
            laravel: 9
          # Исключаем запуск Laravel 10 на PHP 8.4 (несовместимы)
          - php: '8.4'
            laravel: 10

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Start Centrifugo
        run: docker run -d --name centrifugo -p 8000:8000 \
               -e CENTRIFUGO_LOG_LEVEL=debug \ 
               -e CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY="secret" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_PRESENCE="1" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_JOIN_LEAVE="true" \ 
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_FORCE_PUSH_JOIN_LEAVE="true" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_HISTORY_SIZE="100" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_HISTORY_TTL="300s" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_FORCE_RECOVERY="true" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_ALLOW_PUBLISH_FOR_SUBSCRIBER="true" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_ALLOW_PRESENCE_FOR_SUBSCRIBER="true" \
               -e CENTRIFUGO_CHANNEL_WITHOUT_NAMESPACE_ALLOW_HISTORY_FOR_SUBSCRIBER="true" \
               -e CENTRIFUGO_CLIENT_SUBSCRIBE_TO_USER_PERSONAL_CHANNEL_ENABLED="true" \
               -e CENTRIFUGO_HTTP_API_KEY="api-key" \
               centrifugo/centrifugo:v6 \
               centrifugo
      - name: Check container status
        run: docker ps

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://localhost:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 1
          done
        shell: bash

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: PHPUnit Tests
        run: vendor/bin/phpunit
